=== DIEKIH/CN_XML/buoi2_HuynhDangKhoa/buoi2_bai1_HuynhDangKhoa/bai1.1.students/sinhvien.dtd
<!ELEMENT danhsach_sinhvien (sinhvien+)>
<!ELEMENT sinhvien (name, dob, major)>
<!ATTLIST sinhvien
    id ID #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT major (#PCDATA)>

=== DIEKIH/CN_XML/buoi2_HuynhDangKhoa/buoi2_bai1_HuynhDangKhoa/bai1.1.students/sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE danhsach_sinhvien SYSTEM "sinhvien.dtd">
<danhsach_sinhvien>
    <sinhvien id="SV001">
        <name>Huỳnh Đăng Khoa</name>
        <dob>2000-05-15</dob>
        <major>Công nghệ thông tin</major>
    </sinhvien>
    <sinhvien id="SV002">
        <name>Lê Văn Dinh</name>
        <dob>2001-08-22</dob>
        <major>Quản trị kinh doanh</major>
    </sinhvien>
    <sinhvien id="SV003">
        <name>Nguyễn Phúc Khang</name>
        <dob>1999-12-10</dob>
        <major>Kế toán</major>
    </sinhvien>
</danhsach_sinhvien>
