=== DIEKIH/CN_XML/buoi2_HuynhDangKhoa/khoahoc.dtd
<!ELEMENT elearning (course:course+)>
<!ATTLIST elearning
    xmlns:course CDATA #FIXED "http://example.com/course"
    xmlns:instructor CDATA #FIXED "http://example.com/instructor"
    xmlns:student CDATA #FIXED "http://example.com/student"
>

<!ELEMENT course:course (course:title, instructor:instructor, course:students)>
<!ATTLIST course:course
    id ID #REQUIRED
    category CDATA #REQUIRED
>

<!ELEMENT course:title (#PCDATA)>
<!ELEMENT course:students (student:student+)>

<!ELEMENT instructor:instructor (instructor:name, instructor:email)>
<!ATTLIST instructor:instructor
    id ID #REQUIRED
>

<!ELEMENT instructor:name (#PCDATA)>
<!ELEMENT instructor:email (#PCDATA)>

<!ELEMENT student:student (student:name)>
<!ATTLIST student:student
    id ID #REQUIRED
    progress CDATA #REQUIRED
>

<!ELEMENT student:name (#PCDATA)>

=== DIEKIH/CN_XML/huynhdangkhoa/khoahoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elearning SYSTEM "../buoi2_HuynhDangKhoa/khoahoc.dtd">
<elearning xmlns:course="http://example.com/course"
           xmlns:instructor="http://example.com/instructor"
           xmlns:student="http://example.com/student">
    
    <course:course id="C001" category="Lập trình">
        <course:title>Python cơ bản</course:title>
        <instructor:instructor id="I001">
            <instructor:name>Huỳnh Đăng Khoa</instructor:name>
            <instructor:email>huynhdangkhoa@example.com</instructor:email>
        </instructor:instructor>
        <course:students>
            <student:student id="S001" progress="80">
                <student:name>Nguyễn Phúc Khang</student:name>
            </student:student>
            <student:student id="S002" progress="50">
                <student:name>Lê Văn Dinh</student:name>
            </student:student>
        </course:students>
    </course:course>
    
    <course:course id="C002" category="Thiết kế">
        <course:title>Thiết kế đồ họa cơ bản</course:title>
        <instructor:instructor id="I002">
            <instructor:name>Lê Thành Lộc</instructor:name>
            <instructor:email>lethanhloc@example.com</instructor:email>
        </instructor:instructor>
        <course:students>
            <student:student id="S004" progress="70">
                <student:name>Nguyễn Thành Đợi</student:name>
            </student:student>
            <student:student id="S005" progress="85">
                <student:name>Lê Văn Mộng</student:name>
            </student:student>
        </course:students>
    </course:course>
</elearning>
